# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: TayyabPC

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
  displayName: "Use JDK11 by default"
# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloudJEEAPP'
#     organization: 'itayyab'
#     scannerMode: 'Other'        

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'mvn sonar:sonar'    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'pom'
  
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/target/site/jacoco/jacoco.xml'
    #pathToSources: # Optional
    #failIfCoverageEmpty: false # Optional
