# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: TayyabPC

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Sonar Local'
    scannerMode: 'Other'
    extraProperties: |
      sonar.host.url=http://localhost:9000/
      sonar.exclusions=**/*.bin
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'itayyab'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-X'
    goals: 'package deploy'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true
# - task: SonarQubePublish@4
#   inputs:
#     pollingTimeoutSec: '300'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/CCReport43F6D5EF/jacoco.xml'

  
